export const EnglishFAQ = [
    {question: 'How does a Memo affect the V1 Time Car if you have the Case of Plutonium? Is it discarded as usual, or does it go back to your hand because of the Case?', answer: 'It goes back into your hand because of the Case.'},
    {question: 'Why does It’s a Science Experiment make special mention of Canceling the Time Train’s extra play? Do you still get to flip a linchpin before it’s stolen?', answer: 'Yes, the wording on “It’s a Science Experiment” is a little tricky. The other player does still get to flip a Linchpin, but they don’t get the extra card play they would normally get after playing the Time Train.'},
    {question: 'When using a Double Back card, do I have to flip it, or can I leave it the way it is?', answer: 'To review: On the Double Back cards it states, “Flip X linchpin to whichever side you prefer.” In this case “to whichever side you prefer” can mean leaving it the way it is, if that’s the side you prefer.'},
    {question: 'After playing You’re Not Yourself Today, where does the discarded identity card go? Do you add it back into the identity stack and reshuffle (giving a chance to get the same card again) or is it just removed from the game?', answer: 'It should be placed face up at the bottom of the stack of ID cards. If by some chance the game goes on so long that the whole stack gets used, it should be reshuffled when a face up card appears at the top of the stack.'},
    {question: 'Are Time Machines discarded, even when the requirements (Plutonium for v1, Discard a Card for v4, etc) aren’t met?', answer: 'Yes, if you play a Time Machine, it gets discarded. If you do this without meeting any special requirements the Time Machine has, nothing would happen except that you would lose the card. You probably don’t want to do that.'},
    {question: 'Regarding the Second Draw Option, can you do this if you don’t actually have any cards to play?', answer: 'Yes. Any time you are called upon to play a card (Draw one/Play one, a Time Machine effect, etc), you may instead choose to draw a new card.'},
    {question: 'When someone tries to un-invent time travel, and a Mysterious Force card is flipped, is that card reshuffled back into the deck or is it removed from the pile?', answer: 'The card is set aside.'},
    {question: 'The game can run a little long with 5 cards in the B-1 pile. Can you shorten the game by starting with just 3 cards.', answer: 'Absolutely. You could even start with just 2, a real one and a dud, if you want a really short game.'},
    {question: 'At what points can the v4 Time Car be cancelled using one of the Memo cards and what happens to the card that has to be discarded?', answer: 'You can Memo the v4 at any point during the sequence. As noted in another answer, you can save the other player the trouble of deciding what to discard, or you can wait until they’ve discarded their card and even announced what they are changing. That’s all one big game action and as long as you announce your Memo before the next game action, you are fine. However, no matter when you Memo the v4 Time Car, they do not lose the discarded card, just the v4 itself.'},
    {question: 'When activating the newspaper/telegram/fax (Memo) to cancel a Rewind or similar card, do you have to cancel that card, or can you wait to see what was pulled before canceling?', answer: 'You can wait. If someone plays a card like a Rewind, you can choose to cancel the Power Action itself, and save that player the trouble of going any further, or you can wait until they choose a card, and then cancel the card they selected as they use it. Similarly, you can stop someone from ever even going on a time trip by canceling the Time Machine card outright, or you can wait to see what they do with it, and then cancel that. Either way, the Time Machine goes in the trash and the TimeLine remains the same.'},
    {question: 'Can you use Mr. Fusion’s action in addition to your normal draw 1 /play 1 per turn?', answer: 'To refresh, the Mr. Fusion card states "Once per turn, if you have this on the table, you may discard any other item you have on the table and draw 2 cards." In this case, it is a free action. (If it replaced your turn action, it would say so, as it does on the Pizza Hydrator promo card, which requires a turn action to be cashed in.)'},
    {question: 'What happens if Engine Trouble card is played on a Time Machine which was pulled from the discard pile via a Rewind? Does the Time Machine go back into the discard pile?', answer: 'To refresh, Engine Trouble states that it can cancel a Time Machine and send the relevant card back to the hand of the player using it.\n' +
            'When someone Rewinds a card, it is as though the card they pulled from the discard had been played from their hand, so, if Engine Trouble is played on a “rewind” Time Machine, it goes back into the player’s hand.'},
    {question: 'Is it possible to Hitch a Ride after the Truck Full of Manure was played? For example: Player A changed the TimeLine. Then Truck Full of Manure is played and Player B’s turn is canceled. Can Player C use Hitch a Ride now?', answer: 'No. Even though Player B’s turn was canceled, they are still “the previous player,” and they did nothing during their turn (except for dealing with all that manure.)'},
    {question: 'Is it possible to use a Memo (or similar Items) to discard an Artifact/Item that another player has on the table?', answer: 'No. Cancellations only work on cards as they are being played, not cards that are already in play.'},
    {question: 'In the Back to the Future Card Game, is it possible to use Rewind to play a Card that you couldn’t play normally? For example: Can one play the Time Car v1 when he does not have some form of Plutonium?', answer: 'No. When you use Rewind, it becomes the same as if the card you got from the discard pile had been played from your hand. So playing the Time Car v1 via Rewind would be exactly the same as if you played it normally. If you do so when you don’t have the needed Plutonium on the table, nothing happens.'},
    {question: 'Can you Hitch a Ride on someone’s Hitch a Ride?', answer: 'Yes – as long as they successfully changed the timeline.'},
    {question: 'Are there any Hand Limits or Item Limits in the Back to the Future Card Game?', answer: 'No.'},
    {question: 'Can the Lightning Prediction be stolen with Don’t Be So Gullible McFly, or can I use the Lightning Prediction’s free play option to use it up before it can be stolen?', answer: 'Using the Lightning Prediction is a free action, but can only be used on your turn, so you can’t suddenly decide to “use it up” when someone starts to take it from you. So, yes, it can certainly be stolen with So Gullible.'},
    {question: 'In the rules in the Back to the Future Card Game, it says in bold that “You can only claim victory at the END of your turn.” How literally should that be taken? If someone uses the Time Car v3 to flip B-2, must they still play an additional card before the game is over?', answer: 'No, the game ends as soon as time travel is un-invented.'},
    {question: 'When a player is allowed multiple plays on their turn, are there any guidelines for timing between plays?', answer: 'Officially, no… BUT, when playing in any of our games which include interrupt cards which cancel a previous play (Surprise, Memo From Your Future Self, Stop Time) it’s good practice to play a little slower if you happen to be executing multiple plays, so that your opponents have plenty of time to play one of these cards, should they so desire.'},
    {question: 'Can I use a Memo From Your Future Self to stop an Artifact/Item ability? To review: The Memo From Your Future Self (and its variants) occurs in Chrononauts, Early American Chrononauts, and the Back to the Future Card Game. They can be played out of turn to cancel another person’s play as it happens.', answer: 'Basically, yes. In cases where you’d discard that card from play in order to use its power, you could target that card with the Memo, causing it to be discarded without effect. That’s pretty straightforward.\n' +
            '\n' +
            'Note that if a Time Car is being memo’d it’s that card which would go into the discard pile without effect, but any required fuel item would remain (Plutonium, Lightning Prediction, Overpowered Locomotive, or the card discarded to use v4 would go back into the players hand).\n' +
            '\n' +
            'More complicated are Items/Artifacts/Gadgets whose power is passive. These include the (BttF) Gray’s Sports Almanac, Mr. Fusion, The Jade Statue of Tirade, any and all Gadgets. In these cases, you cannot stop the usage of their powers. If their power allows or involves the play of another card, THAT card may be targeted for cancellation via memo, but those cards already in play are not themselves affected by memos.\n' +
            '\n' +
            'For example, when attempting to “feed” Mr. Fusion a card from your the table to gain two cards in your hand, it’s that card which would be targeted by the memo, and discarded with no corresponding benefit, and Mr. Fusion would remain on the table.\n' +
            '\n' +
            'The only time these cards with passive powers could be targeted by a Memo is when they themselves are actually being played to the table, in which case, instead of going into play, they’d go into the discard pile.'},
    {question: 'In the Back To The Future card game, it says that the Fax cannot be used to prevent it’s own theft, but what about countering a counter-memo? If someone tried to steal my Fax with You’re So Gullible, and I counter it with You Steal My Stuff? and they counter with a Memo, can I counter THAT with the Fax, since it wasn’t the original card being used to steal it?', answer: 'No, not if it was the Fax which was the original item being stolen. It cannot participate in any way to intervene in its own theft.'},
    {question: 'If a card lets me do something “once per turn” and I take it out of play, and then somehow put it back into play, is that ability refreshed?', answer: 'If the card says you can only do something once on your turn, it doesn’t matter if the card goes away and comes back again. If you’ve already used it, you’ve already used it. We don’t consider this much of a “memory condition” since you should naturally be able to remember what you have or have not done on your turn, just as you’d remember how many cards you’ve played. If you’re having trouble with a complicated turn, hopefully the other players will help keep you on track as well.'},
    {question: 'Can someone Memo a Memo? i.e. can you stop someone playing a “Memo to Your Future Self” by playing a Memo?', answer: 'Yes, a Memo can indeed be used to stop another Memo. And it’s mighty satisfying when you do!'},
    {question: 'After drawing an extra card after using the Time Car v3, do you get to play it? (or not play, and draw instead, as allowed by the rules regarding playing?)', answer: 'No. You just draw that extra card to your hand, and your turn is over. You only had one play for that turn, and you used it to play the Time Car.'},
    {question: 'Time Train and It’s Your Lucky Day both say to play an extra card after. Is this mandatory?', answer: 'It is never mandatory to play a card. You may choose to draw instead and end your turn (but you must do one or the other). As the rules say “You can exercise this option at any time you are called upon to play a card, such as when you get an extra play because you used a really fancy time machine,” (like the Time Train).'},
    {question: 'When you play Rewind or Quick Trip, and you look through the pile, can you choose not to play those if there’s nothing you want to play? or do you have to goahead with choosing and then playing the card you select?', answer: 'This would ultimately be your call: how lenient do you want to be about letting people take back plays? You should form a house rule about this that everyone is clear on before they start. But for perspective, this is how we usually rule it: you can rollback a rewind but you can\'t rollback a quick trip into the future.'},
    {question: 'Can the B2 DoubleBack card be used at all if another player has the Almanac in play? or is the only option for a player who needs to change that linchpin to hope for an identity change to try and win?', answer: 'Yes, it’s true that the B2 DoubleBack card is pretty much useless if someone else has the Almanac in play, but that doesn’t mean your only option is to try to change your identity. You could try to steal the Almanac with a Don’t Be So Gullible, or by getting the Dust Jacket, or you could try to trash it with Erased From Existence (or possibly You Are Fading Away if the Almanac is their only item in play). If nobody has the Almanac in play, anyone can change B2.'},
    {question: 'What does it mean when a card says its action is a “free play” or a “free action”? Does using a special ability listed on a Keeper or Creeper count as a Play? Does it count as one of your plays for your turn to do this thing?', answer: 'No. That’s the whole point of it being “free”. It does not use one of your plays. Depending on the game we’re talking about (there are cards like this in Chrononauts and Back To The Future, in addition to many in Fluxx editions), you might only be getting one play per turn, and whatever this thing does won’t use up your play for the turn.'},
    {question: 'For cards that let you do something “once per turn”, does that mean once per your turn, or once per each turn in the game?', answer: 'All powers that can be used “once per turn” are only available to you when it’s your turn.'}
];